# Generated by Django 5.1.6 on 2025-02-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_textcontent_image_textcontent_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textcontent',
            name='video',
        ),
        migrations.AddField(
            model_name='textcontent',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
